"""add_payment_method_to_orders

Revision ID: 72de5976e4a1
Revises: fa59a1a3479d
Create Date: 2026-03-09 01:07:03.642092

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72de5976e4a1'
down_revision: Union[str, None] = 'fa59a1a3479d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
